const os = require("os")
console.log("операционая система", os.platform())
console.log("Архитектура процессора", os.arch())
console.log("Информация по процессорам", os.cpus())
console.log("Свободно информации", os.freemem())
console.log("Всего памяти", os.totalmem())
console.log("Домашняя директория", os.homedir())
console.log("Включен", os.uptime())
